version: '3.8'

services:
  daily-report_db:
    image: postgres
    container_name: daily-report_db
    ports:
      - "8902:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: daily-report
    volumes:
      - postgres_data:/var/lib/postgresql/data
  five-minute-report_db:
    image: postgres
    container_name: five-minute-report_db
    ports:
      - "8901:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: daily-report
    volumes:
      - postgres_data:/var/lib/postgresql/data
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "9098:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
volumes:
  postgres_data:
    driver: local
