version: '3.8'

services:
  user_db:
    image: postgres
    container_name: user_db
    ports:
      - "8903:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: user
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
  daily-report_db:
    image: postgres
    container_name: daily-report_db
    ports:
      - "8902:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: daily-report
    volumes:
      - daily_postgres_data:/var/lib/postgresql/data
  five-minute-report_db:
    image: postgres
    container_name: five-minute-report_db
    ports:
      - "8901:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: five-minute-report
    volumes:
      - five_minute_postgres_data:/var/lib/postgresql/data
  mode-report_db:
    image: postgres
    container_name: mode-report_db
    ports:
      - "8904:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: mode-report
    volumes:
      - mode_postgres_data:/var/lib/postgresql/data
  consul:
    image: hashicorp/consul:1.20.1
    hostname: localhost
    ports:
      - 8500:8500
volumes:
  mode_postgres_data:
    driver: local
  daily_postgres_data:
    driver: local
  five_minute_postgres_data:
    driver: local
  user_postgres_data:
    driver: local
