version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    networks:
      - app-net
  auth-server:
    build:
      context: ./auth-server
    container_name: auth-server
    ports:
      - "8083:8083"
    depends_on:
      - user_db
      - config-server
    networks:
      - app-net
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - consul-agent
    networks:
      - app-net
  daily-report:
    build:
      context: ./daily-report
    container_name: daily-report
    ports:
      - "8082:8082"
    depends_on:
      - daily-report_db
      - config-server
    networks:
      - app-net
  five-minute-report:
    build:
      context: ./five-minute-report
    container_name: five-minute-report
    ports:
      - "8081:8081"
    depends_on:
      - five-minute-report_db
      - config-server
    networks:
      - app-net
  mail-service:
    build:
      context: ./mail-service
    container_name: mail-service
    ports:
      - "8100:8100"
    depends_on:
      - config-server
    networks:
      - app-net
  mode-report:
    build:
      context: ./mode-report
    container_name: mode-report
    ports:
      - "8084:8084"
    depends_on:
      - mode-report_db
      - config-server
    networks:
      - app-net
  user_db:
    image: postgres
    container_name: user_db
    ports:
      - "8903:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: user
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  daily-report_db:
    image: postgres
    container_name: daily-report_db
    ports:
      - "8902:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: daily-report
    volumes:
      - daily_postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  five-minute-report_db:
    image: postgres
    container_name: five-minute-report_db
    ports:
      - "8901:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: five-minute-report
    volumes:
      - five_minute_postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  mode-report_db:
    image: postgres
    container_name: mode-report_db
    ports:
      - "8904:5432"
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_admin
      POSTGRES_DB: mode-report
    volumes:
      - mode_postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
  consul-server:
    image: hashicorp/consul:1.20.1
    container_name: consul-server
    ports:
      - "8500:8500"      # HTTP интерфейс
      - "8600:8600/udp"  # DNS
      - "8300:8300"      # RPC
      - "8301:8301"      # Сервер LAN
      - "8301:8301/udp"  # Сервер LAN UDP
      - "8302:8302"      # Сервер WAN
      - "8302:8302/udp"  # Сервер WAN UDP
    volumes:
      - consul-server-data:/consul/data
      - ./config/config.json:/consul/config/config.json
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - app-net
    entrypoint: >
      sh -c "
        consul agent -server -bootstrap-expect=1 \
        -data-dir=/consul/data \
        -node=server-1 \
        -client=0.0.0.0 \
        -ui &
        sleep 5 &&
        consul kv import @/consul/config/config.json &&
        fg
      "
  consul-agent:
    image: hashicorp/consul:1.20.1
    container_name: consul-agent
    depends_on:
      - consul-server
    command: >
      consul agent -node=agent-1
      -data-dir=/consul/data
      -client=0.0.0.0
      -retry-join=consul-server
    volumes:
      - consul-agent-data:/consul/data
    networks:
      - app-net
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Порт для взаимодействия с RabbitMQ
      - "15672:15672"  # Порт для панели управления RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin  # Логин по умолчанию
      RABBITMQ_DEFAULT_PASS: admin  # Пароль по умолчанию
    networks:
      - app-net
volumes:
  mode_postgres_data:
    driver: local
  daily_postgres_data:
    driver: local
  five_minute_postgres_data:
    driver: local
  user_postgres_data:
    driver: local
  consul-server-data:
    driver: local
  consul-agent-data:
    driver: local
  redis_data:
    driver: local

networks:
  app-net:
    driver: bridge
