
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-tls-skip-verify: true
        scheme: https
        enabled: true
        acl-token: "7b3fe245-8649-4071-4f14-e4d187760647"
      config:
        enabled: true
        format: yaml
        acl-token: "7b3fe245-8649-4071-4f14-e4d187760647"
  config:
    import: "consul:"
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    urls:
      -   name: five-minute-report-service
          url: five-minute-report/v3/api-docs
      -   name: daily-report-service
          url: daily-report/v3/api-docs
      -   name: mode-report-service
          url: mode-report/v3/api-docs
      -   name: config-server
          url: /config-server/v3/api-docs
      -   name: auth-server
          url: auth-server/v3/api-docs

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-alias: server
    key-password: changeit
  port: 8080