spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-tls-skip-verify: true
        scheme: https
        enabled: true
        acl-token: "7b3fe245-8649-4071-4f14-e4d187760647"
      config:
        enabled: true
        format: yaml
        acl-token: "7b3fe245-8649-4071-4f14-e4d187760647"
  config:
    import: "consul:"
  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    urls:
      -   name: factory-monitoring-service
          url: factory-monitoring-service/v3/api-docs
      -   name: config-server
          url: /config-server/v3/api-docs
      -   name: auth-server
          url: auth-server/v3/api-docs