spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: api-gateway:${random.uuid}
      config:
        enabled: true
        format: yaml
  config:
    import: "consul:"
