spring:
  application:
    name: mail-service
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        enabled: true
        acl-token: "61a2b669-7242-27c0-5314-9fad53bb5a8e"
      config:
        enabled: true
        format: key_value
        acl-token: "61a2b669-7242-27c0-5314-9fad53bb5a8e"
  config:
    import: "consul:"