spring:
  application:
    name: daily-report
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        enabled: true
      config:
        enabled: true
  config:
    import: "consul:"
