spring:
  application:
    name: daily-report
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        enabled: true
        acl-token: "3a4ecff8-c781-4103-8911-355fb51e4a6c"
      config:
        enabled: true
        format: key_value
        acl-token: "3a4ecff8-c781-4103-8911-355fb51e4a6c"
  config:
    import: "consul:"
