spring:
  application:
    name: five-minute-report
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
      config:
        enabled: true
  config:
    import: "consul:"
