spring:
  application:
    name: five-minute-report
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        enabled: true
        acl-token: "13b048a0-84ba-4389-53a9-ddcc08d5589d"
      config:
        enabled: true
        acl-token: "13b048a0-84ba-4389-53a9-ddcc08d5589d"
  config:
    import: "consul:"
