spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: five-minute-report-service
          uri: lb://FIVE-MINUTE-REPORT
          predicates:
            - Path=/api/v1/five-minute-report/**
        - id: daily-report-service
          uri: lb://DAILY-REPORT
          predicates:
            - Path=/api/v1/daily-report/**
server:
  port: 8080