spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: five-minute-report-service
          uri: lb://FIVE-MINUTE-REPORT
          predicates:
            - Path=/api/v1/five-minute-report/**
        - id: daily-report-service
          uri: lb://DAILY-REPORT
          predicates:
            - Path=/api/v1/daily-report/**
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth-server/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000, http://127.0.0.1:3001, http://localhost:3000, localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
server:
  port: 8080