spring:
  datasource:
    url: jdbc:postgresql://localhost:8904/mode-report
    username: postgres_admin
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8084
