spring:
  application:
    name: mode-report
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        enabled: true
        acl-token: "97e16953-fdf0-8c6e-e1b8-f7a48b1c8d1d"
      config:
        enabled: true
        format: key_value
        acl-token: "97e16953-fdf0-8c6e-e1b8-f7a48b1c8d1d"
  config:
    import: "consul:"
