spring:
  application:
    name: mode-report
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        enabled: true
        acl-token: "6d2bce06-9955-c681-4afb-c1754e9ffc83"
      config:
        enabled: true
        acl-token: "6d2bce06-9955-c681-4afb-c1754e9ffc83"
  config:
    import: "consul:"
