spring:
  application:
    name: config-server
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
      discovery:
        enabled: true
        register: true
        service-name: config-server
  config:
    import: "consul:"
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"