spring:
  application:
    name: config-server
  cloud:
    consul:
      host: consul-server
      port: 8500
      config:
        enabled: true
        acl-token: "3a4ecff8-c781-4103-8911-355fb51e4a6c"
      discovery:
        enabled: true
        register: true
        service-name: config-server
        acl-token: "3a4ecff8-c781-4103-8911-355fb51e4a6c"
  config:
    import: "consul:"
management:
  endpoints:
    web:
      exposure:
        include: "*"