spring:
  application:
    name: config-server
  cloud:
    consul:
      host: consul-server
      port: 8500
      config:
        enabled: true
        acl-token: "61a2b669-7242-27c0-5314-9fad53bb5a8e"
      discovery:
        enabled: true
        register: true
        service-name: config-server
        acl-token: "61a2b669-7242-27c0-5314-9fad53bb5a8e"
  config:
    import: "consul:"
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"